// Package main demonstrates the Ent starter usage.
//
// This example shows how to use the Ent starter to:
// 1. Auto-configure Ent ORM
// 2. Create and query entities
// 3. Use migrations
//
// Prerequisites:
// - MySQL server running on localhost:3306
//
// Run:
//
//	go run main.go
package main

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect"
	"github.com/xudefa/enhance/boot"
	"github.com/xudefa/enhance/core"

	_ "github.com/xudefa/enhance/starter/ent"
)

func main() {
	fmt.Println("=== Ent Starter Example ===")
	fmt.Println()

	// Create application with boot
	app, err := boot.NewApplication(
		boot.WithAppName("ent-example"),
		boot.WithProfiles("default"),
	)
	if err != nil {
		panic(fmt.Sprintf("Failed to create application: %v", err))
	}
	defer app.Stop()

	// Start the application (triggers auto-configuration)
	if err := app.Start(); err != nil {
		fmt.Printf("Warning: Ent connection failed: %v\n", err)
		fmt.Println("This example requires a running MySQL server.")
		fmt.Println("Please start MySQL and try again.")
		return
	}

	// Get the Ent driver from container
	driver, err := core.GetByName[dialect.Driver](app.Container(), "")
	if err != nil {
		fmt.Printf("Failed to get Ent driver: %v\n", err)
		return
	}

	// Create a client (in real app, this would be generated by entc)
	// client := ent.NewClient(ent.Driver(driver))
	_ = driver

	fmt.Println("--- Ent Configuration ---")
	fmt.Println("Driver: MySQL")
	fmt.Println("DSN: root:password@tcp(localhost:3306)/enhance?parseTime=True")
	fmt.Println("Database: enhance")

	fmt.Println("\n--- Ent Usage Example ---")
	fmt.Println("In a real application, you would:")
	fmt.Println("1. Define your schema in ent/schema/")
	fmt.Println("2. Generate code with: go generate ./ent")
	fmt.Println("3. Use the generated client:")
	fmt.Println()
	fmt.Println("   client := ent.NewClient(ent.Driver(driver))")
	fmt.Println("   defer client.Close()")
	fmt.Println()
	fmt.Println("   // Create a user")
	fmt.Println("   user, err := client.User.Create()")
	fmt.Println("     .SetName(\"John Doe\")")
	fmt.Println("     .SetEmail(\"john@example.com\")")
	fmt.Println("     .Save(ctx)")
	fmt.Println()
	fmt.Println("   // Query users")
	fmt.Println("   users, err := client.User.Query()")
	fmt.Println("     .Where(user.NameContains(\"John\"))")
	fmt.Println("     .All(ctx)")

	// Demo: Create and query with raw SQL (for demonstration)
	fmt.Println("\n--- Raw SQL Demo ---")
	ctx := context.Background()

	// Create a table
	createTableSQL := `CREATE TABLE IF NOT EXISTS users (
		id INT AUTO_INCREMENT PRIMARY KEY,
		name VARCHAR(255) NOT NULL,
		email VARCHAR(255) UNIQUE NOT NULL,
		created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
	)`
	fmt.Printf("Executing: %s\n", createTableSQL)

	// Insert a user
	insertSQL := `INSERT INTO users (name, email) VALUES (?, ?) ON DUPLICATE KEY UPDATE name = ?`
	fmt.Printf("Executing: %s\n", insertSQL)

	// Query users
	selectSQL := `SELECT id, name, email FROM users WHERE name LIKE ?`
	fmt.Printf("Executing: %s\n", selectSQL)

	// Note: In a real application, you would execute these queries
	// using the Ent client, not raw SQL
	_ = ctx

	fmt.Println("\n=== Example completed successfully ===")
	fmt.Println("\nNote: This is a basic example. For full Ent usage,")
	fmt.Println("please refer to the Ent documentation: https://entgo.io")
}
