package generator

import (
	"fmt"
	"strings"
	"text/template"
)

// StaticProxyTemplate 静态代理模板（零反射）
//
// 生成的代理代码直接内联通知链，完全消除运行时反射调用。
const StaticProxyTemplate = `// Code generated by enhance aop gen. DO NOT EDIT.
// source: {{.SourceFile}}

package {{.Package}}

import (
	{{- range .Imports}}
	"{{.}}"
	{{- end}}
)

// {{.ProxyName}} is the AOP proxy for {{.TargetName}}.
type {{.ProxyName}} struct {
	target *{{.TargetName}}
	{{- range .AdviceFields}}
	{{.Name}} {{.Type}}
	{{- end}}
}

// New{{.ProxyName}} creates a new proxy instance.
func New{{.ProxyName}}(target *{{.TargetName}} {{- range .AdviceFields}}, {{.Name}} {{.Type}}{{- end}}) *{{.ProxyName}} {
	return &{{.ProxyName}}{
		target: target,
		{{- range .AdviceFields}}
		{{.Name}}: {{.Name}},
		{{- end}}
	}
}

{{- range .Methods}}
{{- $method := .}}
func (p *{{$.ProxyName}}) {{.Name}}({{.ParamsStr}}) {{.ResultsStr}} {
{{- if .HasAspects}}
	// AOP advice chain for {{.Name}}
{{- if .BeforeAdvices}}
	// Before 通知
{{- range .BeforeAdvices}}
	p.{{.AdviceField}}[0](p.target{{if $method.HasParams}}, {{$method.ArgsList}}{{end}})
{{- end}}
{{- end}}
{{- if .HasReturnValue}}
	{{- if .AfterReturningAdvices}}
	result := p.target.{{.Name}}({{.ArgsList}})
	// AfterReturning advices
{{- range .AfterReturningAdvices}}
	p.{{.AdviceField}}[0](result)
{{- end}}
	return result
	{{- else}}
	return p.target.{{.Name}}({{.ArgsList}})
	{{- end}}
{{- else}}
	p.target.{{.Name}}({{.ArgsList}})
{{- if .AfterAdvices}}
	// After 通知
{{- range .AfterAdvices}}
	p.{{.AdviceField}}[0]()
{{- end}}
{{- end}}
	return
{{- end}}
{{- else}}
	{{- if .HasReturnValue}}
	return p.target.{{.Name}}({{.ArgsList}})
	{{- else}}
	p.target.{{.Name}}({{.ArgsList}})
	return
	{{- end}}
{{- end}}
}
{{- end}}
`

// InterfaceProxyTemplate 接口代理模板
const InterfaceProxyTemplate = `// Code generated by enhance aop gen. DO NOT EDIT.
// source: {{.SourceFile}}

package {{.Package}}

import (
	{{- range .Imports}}
	"{{.}}"
	{{- end}}
)

// {{.ProxyName}} is the AOP proxy for {{.InterfaceName}}.
type {{.ProxyName}} struct {
	target {{.InterfaceName}}
	{{- range .AdviceFields}}
	{{.Name}} {{.Type}}
	{{- end}}
}

// New{{.ProxyName}} creates a new proxy instance.
func New{{.ProxyName}}(target {{.InterfaceName}} {{- range .AdviceFields}}, {{.Name}} {{.Type}}{{- end}}) *{{.ProxyName}} {
	return &{{.ProxyName}}{
		target: target,
		{{- range .AdviceFields}}
		{{.Name}}: {{.Name}},
		{{- end}}
	}
}

{{- range .Methods}}
{{- $method := .}}
func (p *{{$.ProxyName}}) {{.Name}}({{.ParamsStr}}) {{.ResultsStr}} {
{{- if .HasAspects}}
{{- if .BeforeAdvices}}
{{- range .BeforeAdvices}}
	p.{{.AdviceField}}[0](p.target{{if $method.HasParams}}, {{$method.ArgsList}}{{end}})
{{- end}}
{{- end}}
{{- if .HasReturnValue}}
	return p.target.{{.Name}}({{.ArgsList}})
{{- else}}
	p.target.{{.Name}}({{.ArgsList}})
	return
{{- end}}
{{- else}}
{{- if .HasReturnValue}}
	return p.target.{{.Name}}({{.ArgsList}})
{{- else}}
	p.target.{{.Name}}({{.ArgsList}})
	return
{{- end}}
{{- end}}
}
{{- end}}
`

// RenderStaticProxy 渲染静态代理代码
func RenderStaticProxy(data *StaticProxyTemplateData) (string, error) {
	tmpl, err := template.New("static_proxy").Parse(StaticProxyTemplate)
	if err != nil {
		return "", fmt.Errorf("parse template: %w", err)
	}

	var buf strings.Builder
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", fmt.Errorf("execute template: %w", err)
	}

	return buf.String(), nil
}

// RenderInterfaceProxy 渲染接口代理代码
func RenderInterfaceProxy(data *InterfaceProxyTemplateData) (string, error) {
	tmpl, err := template.New("interface_proxy").Parse(InterfaceProxyTemplate)
	if err != nil {
		return "", fmt.Errorf("parse template: %w", err)
	}

	var buf strings.Builder
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", fmt.Errorf("execute template: %w", err)
	}

	return buf.String(), nil
}

// StaticProxyTemplateData 静态代理模板数据
type StaticProxyTemplateData struct {
	Package      string
	ProxyName    string
	TargetName   string
	SourceFile   string
	Imports      []string
	Methods      []StaticMethodInfo
	AdviceFields []AdviceField
}

// InterfaceProxyTemplateData 接口代理模板数据
type InterfaceProxyTemplateData struct {
	Package       string
	ProxyName     string
	InterfaceName string
	SourceFile    string
	Imports       []string
	Methods       []StaticMethodInfo
	AdviceFields  []AdviceField
}

// StaticMethodInfo 静态代理方法信息
type StaticMethodInfo struct {
	Name                  string
	Params                []ParamInfo
	Results               []string
	ParamsStr             string
	ResultsStr            string
	ArgsList              string
	HasParams             bool
	HasReturnValue        bool
	HasAspects            bool
	BeforeAdvices         []AdviceRef
	AfterAdvices          []AdviceRef
	AfterReturningAdvices []AdviceRef
	AroundAdvice          *AdviceRef
}

// AdviceField 通知字段
type AdviceField struct {
	Name string
	Type string
}

// AdviceRef 通知引用
type AdviceRef struct {
	AdviceField string
}
