package generator

import (
	"strings"
)

// simpleProxyTemplate 简单代理模板（不启用 AOP 时使用）
const simpleProxyTemplate = `// Code generated by goaop. DO NOT EDIT.
package {{.Package}}

import (
	{{- range .Imports}}
	"{{.}}"
	{{- end}}
)

type {{.ProxyName}} struct {
	target *{{.TargetName}}
}

func New{{.ProxyName}}(target *{{.TargetName}}) *{{.ProxyName}} {
	return &{{.ProxyName}}{target: target}
}

{{- range .Methods}}
func (p *{{$.ProxyName}}) {{.Name}}({{.ParamsStr}}) {{.ResultsStr}} {
	return p.target.{{.Name}}({{.ArgsList}})
}
{{- end}}

func init() {
	core.RegisterFactory(globalContainer, func(c core.Container) (*{{.ProxyName}}, error) {
		target := &{{.TargetName}}{}
		{{- range .Dependencies}}
		if dep, err := core.GetByType[{{.}}](c); err == nil {
			target.{{.}} = dep
		}
		{{- end}}
		return New{{.ProxyName}}(target), nil
	}, core.Singleton())
}
`

// staticAopProxyTemplate 静态 AOP 代理模板（零反射开销）
//
// 生成的代码直接内联通知链，完全消除运行时反射调用。
const staticAopProxyTemplate = `// Code generated by goaop. DO NOT EDIT.
package {{.Package}}

import (
	{{- range .Imports}}
	"{{.}}"
	{{- end}}
)

type {{.ProxyName}} struct {
	target *{{.TargetName}}
}

func New{{.ProxyName}}(target *{{.TargetName}}) *{{.ProxyName}} {
	return &{{.ProxyName}}{target: target}
}

{{- range .Methods}}
{{- $method := .}}
func (p *{{$.ProxyName}}) {{.Name}}({{.ParamsStr}}) {{.ResultsStr}} {
{{- if .HasAspects}}
{{- if .HasBeforeAdvices}}
{{- range .BeforeAdvices}}
	{{.AdviceFunc}}(p.target{{if $method.HasParams}}, {{$method.ArgsList}}{{end}})
{{- end}}
{{- end}}
{{- if .HasReturnValue}}
	return p.target.{{.Name}}({{.ArgsList}})
{{- else}}
	p.target.{{.Name}}({{.ArgsList}})
	return
{{- end}}
{{- else}}
{{- if .HasReturnValue}}
	return p.target.{{.Name}}({{.ArgsList}})
{{- else}}
	p.target.{{.Name}}({{.ArgsList}})
	return
{{- end}}
{{- end}}
}
{{- end}}

func init() {
	core.RegisterFactory(globalContainer, func(c core.Container) (*{{.ProxyName}}, error) {
		target := &{{.TargetName}}{}
		{{- range .Dependencies}}
		if dep, err := core.GetByType[{{.}}](c); err == nil {
			target.{{.}} = dep
		}
		{{- end}}
		return New{{.ProxyName}}(target), nil
	}, core.Singleton())
}
`

// staticInterfaceProxyTemplate 静态接口代理模板（零反射开销）
//
// 为接口生成代理实现，完全消除运行时反射调用。
const staticInterfaceProxyTemplate = `// Code generated by goaop. DO NOT EDIT.
package {{.Package}}

import (
	{{- range .Imports}}
	"{{.}}"
	{{- end}}
)

type {{.ProxyName}} struct {
	target {{.TargetName}}
}

func New{{.ProxyName}}(target {{.TargetName}}) *{{.ProxyName}} {
	return &{{.ProxyName}}{target: target}
}

{{- range .Methods}}
{{- $method := .}}
func (p *{{$.ProxyName}}) {{.Name}}({{.ParamsStr}}) {{.ResultsStr}} {
{{- if .HasAspects}}
{{- if .HasBeforeAdvices}}
{{- range .BeforeAdvices}}
	{{.AdviceFunc}}(p.target{{if $method.HasParams}}, {{$method.ArgsList}}{{end}})
{{- end}}
{{- end}}
{{- if .HasReturnValue}}
	return p.target.{{.Name}}({{.ArgsList}})
{{- else}}
	p.target.{{.Name}}({{.ArgsList}})
	return
{{- end}}
{{- else}}
{{- if .HasReturnValue}}
	return p.target.{{.Name}}({{.ArgsList}})
{{- else}}
	p.target.{{.Name}}({{.ArgsList}})
	return
{{- end}}
{{- end}}
}
{{- end}}

func init() {
	core.RegisterFactory(globalContainer, func(c core.Container) (*{{.ProxyName}}, error) {
		var target {{.TargetName}}
		if t, err := core.GetByType[{{.TargetName}}](c); err == nil {
			target = t
		}
		return New{{.ProxyName}}(target), nil
	}, core.Singleton())
}
`

// aopProxyTemplate AOP 增强代理模板（启用 AOP 时使用）
const aopProxyTemplate = `// Code generated by goaop. DO NOT EDIT.
package {{.Package}}

import (
	{{- range .Imports}}
	"{{.}}"
	{{- end}}
)

type {{.ProxyName}} struct {
	target  *{{.TargetName}}
	aspects []*aop.AspectMeta
}

func New{{.ProxyName}}(target *{{.TargetName}}) *{{.ProxyName}} {
	return &{{.ProxyName}}{
		target:  target,
		aspects: []*aop.AspectMeta{
			{{- range .Aspects}}
			&{
				PointCut: aop.MatchByName("{{.MethodName}}"),
				Advice:   aop.{{.AdviceType}}({{.AdviceFunc}}),
				Order:    {{.Order}},
			},
			{{- end}}
		},
	}
}

{{- range .Aspects}}
func {{.AdviceFunc}}(jp aop.JoinPoint{{if eq .AdviceType "Around"}}, proceed aop.ProceedFunc{{end}}) {{if eq .AdviceType "Around"}}any{{end}} {
	aspect := &{{.AspectName}}{}
	{{- if eq .AdviceType "Before"}}
	aspect.{{.AspectMethodName}}(jp)
	{{- else if eq .AdviceType "After"}}
	aspect.{{.AspectMethodName}}(jp)
	{{- else if eq .AdviceType "Around"}}
	return aspect.{{.AspectMethodName}}(jp, proceed)
	{{- end}}
}
{{- end}}

{{- range .Methods}}
func (p *{{$.ProxyName}}) {{.Name}}({{.ParamsStr}}) {{.ResultsStr}} {
	jp := &aop.MethodInvocation{
		MethodName: "{{.Name}}",
		Func:       p.target.{{.Name}},
		Params:     []any{ {{.ArgsList}} },
		Object:     p.target,
	}
	result := aop.ExecuteChainWithPtrs(jp, p.aspects)
	{{- if .NoReturn}}
	return
	{{- else if .HasMultipleReturns}}
	if tuple, ok := result.([]any); ok {
		{{- if .HasError}}
		if len(tuple) > 0 {
			if err, ok := tuple[len(tuple)-1].(error); ok && err != nil {
				return {{.ReturnValuesWithError}}
			}
		}
		{{- end}}
		return {{.ReturnValuesFromTuple}}
	}
	return {{.ReturnValuesFallback}}
	{{- else if .HasSingleErrorReturn}}
	if err, ok := result.(error); ok {
		return err
	}
	return nil
	{{- else if .HasSingleReturn}}
	if typed, ok := result.({{.SingleReturnType}}); ok {
		return typed
	}
	return nil
	{{- end}}
}
{{- end}}

func init() {
	core.RegisterFactory(globalContainer, func(c core.Container) (*{{.ProxyName}}, error) {
		target := &{{.TargetName}}{}
		{{- range .Dependencies}}
		if dep, err := core.GetByType[{{.}}](c); err == nil {
			target.{{.}} = dep
		}
		{{- end}}
		return New{{.ProxyName}}(target), nil
	}, core.Singleton())
}
`

// adviceAdapterTemplate 通知适配器模板
const adviceAdapterTemplate = `// Code generated by goaop. DO NOT EDIT.
//go:build goaop
// +build goaop

package {{.Package}}

import (
	"github.com/xudefa/enhance/aop"
)

{{- range .Adapters}}
func {{.FuncName}}(jp aop.JoinPoint{{if .IsAround}}, proceed aop.ProceedFunc{{end}}) {{if .HasReturn}}any{{end}} {
	aspect := &{{.AspectType}}{}
	{{- if .IsAround}}
	return aspect.{{.MethodName}}(jp, proceed)
	{{- else}}
	aspect.{{.MethodName}}(jp)
	{{- end}}
}
{{- end}}
`

// unused import guard
var _ = strings.TrimSpace
