package generator

import (
	"strings"
)

// simpleProxyTemplate 简单代理模板（不启用 AOP 时使用）
const simpleProxyTemplate = `// Code generated by goaop. DO NOT EDIT.
package {{.Package}}

import (
	{{- range .Imports}}
	"{{.}}"
	{{- end}}
)

var {{.ProxyName}}Container = core.NewContainer()

type {{.ProxyName}} struct {
	Target {{if .IsInterface}}{{.TargetName}}{{else}}*{{.TargetName}}{{end}}
}

func New{{.ProxyName}}(target {{if .IsInterface}}{{.TargetName}}{{else}}*{{.TargetName}}{{end}}) *{{.ProxyName}} {
	return &{{.ProxyName}}{Target: target}
}

{{- range .Methods}}
func (p *{{$.ProxyName}}) {{.Name}}({{.ParamsStr}}) {{.ResultsStr}} {
	return p.Target.{{.Name}}({{.ArgsList}})
}
{{- end}}

func init() {
	core.Register[*{{.ProxyName}}]({{.ProxyName}}Container,
		core.WithFactory[*{{.ProxyName}}](func(c ...any) (any, error) {
			{{- if .IsInterface}}
			var target {{.TargetName}}
			if t, err := core.GetByName[{{.TargetName}}]({{$.ProxyName}}Container, ""); err == nil {
				target = t
			}
			{{- else}}
			target := &{{.TargetName}}{}
			{{- end}}
			return New{{.ProxyName}}(target), nil
		}),
	)
}
`

// staticAopProxyTemplate 静态 AOP 代理模板（零反射开销）
//
// 生成的代码直接内联通知链，完全消除运行时反射调用。
const staticAopProxyTemplate = `// Code generated by goaop. DO NOT EDIT.
package {{.Package}}

import (
	{{- range .Imports}}
	"{{.}}"
	{{- end}}
)

var {{.ProxyName}}Container = core.NewContainer()

type {{.ProxyName}} struct {
	Target  *{{.TargetName}}
	aspects []*aop.AspectMeta
}

func New{{.ProxyName}}(target *{{.TargetName}}) *{{.ProxyName}} {
	return &{{.ProxyName}}{
		Target: target,
		aspects: []*aop.AspectMeta{
			{{- range .Aspects}}
			&aop.AspectMeta{
				PointCut: aop.MatchByName("{{.MethodName}}"),
				Advice:   aop.{{.AdviceType}}({{.AdviceFunc}}),
				Order:    {{.Order}},
			},
			{{- end}}
		},
	}
}

{{- range uniqueAdviceFuncs .Aspects}}
{{- if .AspectName}}
{{- if eq .AdviceType "Before"}}
func {{.AdviceFunc}}(jp aop.JoinPoint) {
	aspect := &{{.AspectName}}{}
	aspect.{{.AspectMethodName}}(jp)
}
{{- else if eq .AdviceType "After"}}
func {{.AdviceFunc}}(jp aop.JoinPoint) {
	aspect := &{{.AspectName}}{}
	aspect.{{.AspectMethodName}}(jp)
}
{{- else if eq .AdviceType "Around"}}
func {{.AdviceFunc}}(jp aop.JoinPoint, proceed func() any) any {
	aspect := &{{.AspectName}}{}
	return aspect.{{.AspectMethodName}}(jp, aop.ProceedFunc(func(args ...any) any { return proceed() }))
}
{{- else if eq .AdviceType "AfterReturning"}}
func {{.AdviceFunc}}(jp aop.JoinPoint, result any) {
	aspect := &{{.AspectName}}{}
	aspect.{{.AspectMethodName}}(jp, result)
}
{{- else if eq .AdviceType "AfterThrowing"}}
func {{.AdviceFunc}}(jp aop.JoinPoint, err error) {
	aspect := &{{.AspectName}}{}
	aspect.{{.AspectMethodName}}(jp, err)
}
{{- end}}
{{- end}}
{{- end}}

{{- range .Methods}}
func (p *{{$.ProxyName}}) {{.Name}}({{.ParamsStr}}) {{.ResultsStr}} {
{{- if .HasAspects}}
	jp := &aop.MethodInvocation{
		MethodName: "{{.Name}}",
		Func:       p.Target.{{.Name}},
		Params:     []any{ {{.ArgsList}} },
		Object:     p.Target,
	}
	result := aop.ExecuteChain(jp, p.aspects)
	{{- if .NoReturn}}
	return
	{{- else if .HasMultipleReturns}}
	if tuple, ok := result.([]any); ok {
		{{- if .HasError}}
		if len(tuple) > 0 {
			if err, ok := tuple[len(tuple)-1].(error); ok && err != nil {
				return {{.ReturnValuesWithError}}
			}
		}
		{{- end}}
		return {{.ReturnValuesFromTuple}}
	}
	panic("aop: unexpected result type for {{.Name}}")
	{{- else if .HasSingleErrorReturn}}
	if err, ok := result.(error); ok {
		return err
	}
	return nil
	{{- else if .HasSingleReturn}}
	if typed, ok := result.({{.SingleReturnType}}); ok {
		return typed
	}
	panic("aop: unexpected result type for {{.Name}}")
	{{- end}}
{{- else}}
	{{- if .HasReturnValue}}
	return p.Target.{{.Name}}({{.ArgsList}})
	{{- else}}
	p.Target.{{.Name}}({{.ArgsList}})
	return
	{{- end}}
{{- end}}
}
{{- end}}

func init() {
	core.Register[*{{.ProxyName}}]({{.ProxyName}}Container,
		core.WithFactory[*{{.ProxyName}}](func(c ...any) (any, error) {
			target := &{{.TargetName}}{}
			return New{{.ProxyName}}(target), nil
		}),
	)
}
`

// staticInterfaceProxyTemplate 静态接口代理模板（零反射开销）
//
// 为接口生成代理实现，完全消除运行时反射调用。
const staticInterfaceProxyTemplate = `// Code generated by goaop. DO NOT EDIT.
package {{.Package}}

import (
	{{- range .Imports}}
	"{{.}}"
	{{- end}}
)

var {{.ProxyName}}Container = core.NewContainer()

type {{.ProxyName}} struct {
	Target  {{.TargetName}}
	aspects []*aop.AspectMeta
}

func New{{.ProxyName}}(target {{.TargetName}}) *{{.ProxyName}} {
	return &{{.ProxyName}}{
		Target: target,
		aspects: []*aop.AspectMeta{
			{{- range .Aspects}}
			&aop.AspectMeta{
				PointCut: aop.MatchByName("{{.MethodName}}"),
				Advice:   aop.{{.AdviceType}}({{.AdviceFunc}}),
				Order:    {{.Order}},
			},
			{{- end}}
		},
	}
}

{{- range uniqueAdviceFuncs .Aspects}}
{{- if .AspectName}}
{{- if eq .AdviceType "Before"}}
func {{.AdviceFunc}}(jp aop.JoinPoint) {
	aspect := &{{.AspectName}}{}
	aspect.{{.AspectMethodName}}(jp)
}
{{- else if eq .AdviceType "After"}}
func {{.AdviceFunc}}(jp aop.JoinPoint) {
	aspect := &{{.AspectName}}{}
	aspect.{{.AspectMethodName}}(jp)
}
{{- else if eq .AdviceType "Around"}}
func {{.AdviceFunc}}(jp aop.JoinPoint, proceed func() any) any {
	aspect := &{{.AspectName}}{}
	return aspect.{{.AspectMethodName}}(jp, aop.ProceedFunc(func(args ...any) any { return proceed() }))
}
{{- else if eq .AdviceType "AfterReturning"}}
func {{.AdviceFunc}}(jp aop.JoinPoint, result any) {
	aspect := &{{.AspectName}}{}
	aspect.{{.AspectMethodName}}(jp, result)
}
{{- else if eq .AdviceType "AfterThrowing"}}
func {{.AdviceFunc}}(jp aop.JoinPoint, err error) {
	aspect := &{{.AspectName}}{}
	aspect.{{.AspectMethodName}}(jp, err)
}
{{- end}}
{{- end}}
{{- end}}

{{- range .Methods}}
func (p *{{$.ProxyName}}) {{.Name}}({{.ParamsStr}}) {{.ResultsStr}} {
{{- if .HasAspects}}
	jp := &aop.MethodInvocation{
		MethodName: "{{.Name}}",
		Func:       p.Target.{{.Name}},
		Params:     []any{ {{.ArgsList}} },
		Object:     p.Target,
	}
	result := aop.ExecuteChain(jp, p.aspects)
	{{- if .NoReturn}}
	return
	{{- else if .HasMultipleReturns}}
	if tuple, ok := result.([]any); ok {
		{{- if .HasError}}
		if len(tuple) > 0 {
			if err, ok := tuple[len(tuple)-1].(error); ok && err != nil {
				return {{.ReturnValuesWithError}}
			}
		}
		{{- end}}
		return {{.ReturnValuesFromTuple}}
	}
	panic("aop: unexpected result type for {{.Name}}")
	{{- else if .HasSingleErrorReturn}}
	if err, ok := result.(error); ok {
		return err
	}
	return nil
	{{- else if .HasSingleReturn}}
	if typed, ok := result.({{.SingleReturnType}}); ok {
		return typed
	}
	panic("aop: unexpected result type for {{.Name}}")
	{{- end}}
{{- else}}
	{{- if .HasReturnValue}}
	return p.Target.{{.Name}}({{.ArgsList}})
	{{- else}}
	p.Target.{{.Name}}({{.ArgsList}})
	return
	{{- end}}
{{- end}}
}
{{- end}}

func init() {
	core.Register[*{{.ProxyName}}]({{.ProxyName}}Container,
		core.WithFactory[*{{.ProxyName}}](func(c ...any) (any, error) {
			var target {{.TargetName}}
			if t, err := core.GetByName[{{.TargetName}}]({{.ProxyName}}Container, ""); err == nil {
				target = t
			}
			return New{{.ProxyName}}(target), nil
		}),
	)
}
`

// aopProxyTemplate AOP 增强代理模板（启用 AOP 时使用）
const aopProxyTemplate = `// Code generated by goaop. DO NOT EDIT.
package {{.Package}}

import (
	{{- range .Imports}}
	"{{.}}"
	{{- end}}
)

var {{.ProxyName}}Container = core.NewContainer()

type {{.ProxyName}} struct {
	Target  {{if .IsInterface}}{{.TargetName}}{{else}}*{{.TargetName}}{{end}}
	aspects []*aop.AspectMeta
}

func New{{.ProxyName}}(target {{if .IsInterface}}{{.TargetName}}{{else}}*{{.TargetName}}{{end}}) *{{.ProxyName}} {
	return &{{.ProxyName}}{
		Target: target,
		aspects: []*aop.AspectMeta{
			{{- range .Aspects}}
			&aop.AspectMeta{
				PointCut: aop.MatchByName("{{.MethodName}}"),
				Advice:   aop.{{.AdviceType}}({{.AdviceFunc}}),
				Order:    {{.Order}},
			},
			{{- end}}
		},
	}
}

{{- range uniqueAdviceFuncs .Aspects}}
{{- if .AspectName}}
{{- if eq .AdviceType "Before"}}
func {{.AdviceFunc}}(jp aop.JoinPoint) {
	aspect := &{{.AspectName}}{}
	aspect.{{.AspectMethodName}}(jp)
}
{{- else if eq .AdviceType "After"}}
func {{.AdviceFunc}}(jp aop.JoinPoint) {
	aspect := &{{.AspectName}}{}
	aspect.{{.AspectMethodName}}(jp)
}
{{- else if eq .AdviceType "Around"}}
func {{.AdviceFunc}}(jp aop.JoinPoint, proceed func() any) any {
	aspect := &{{.AspectName}}{}
	return aspect.{{.AspectMethodName}}(jp, aop.ProceedFunc(func(args ...any) any { return proceed() }))
}
{{- else if eq .AdviceType "AfterReturning"}}
func {{.AdviceFunc}}(jp aop.JoinPoint, result any) {
	aspect := &{{.AspectName}}{}
	aspect.{{.AspectMethodName}}(jp, result)
}
{{- else if eq .AdviceType "AfterThrowing"}}
func {{.AdviceFunc}}(jp aop.JoinPoint, err error) {
	aspect := &{{.AspectName}}{}
	aspect.{{.AspectMethodName}}(jp, err)
}
{{- end}}
{{- end}}
{{- end}}

{{- range .Methods}}
func (p *{{$.ProxyName}}) {{.Name}}({{.ParamsStr}}) {{.ResultsStr}} {
	jp := &aop.MethodInvocation{
		MethodName: "{{.Name}}",
		Func:       p.Target.{{.Name}},
		Params:     []any{ {{.ArgsList}} },
		Object:     p.Target,
	}
	result := aop.ExecuteChain(jp, p.aspects)
	{{- if .NoReturn}}
	return
	{{- else if .HasMultipleReturns}}
	if tuple, ok := result.([]any); ok {
		{{- if .HasError}}
		if len(tuple) > 0 {
			if err, ok := tuple[len(tuple)-1].(error); ok && err != nil {
				return {{.ReturnValuesWithError}}
			}
		}
		{{- end}}
		return {{.ReturnValuesFromTuple}}
	}
	panic("aop: unexpected result type for {{.Name}}")
	{{- else if .HasSingleErrorReturn}}
	if err, ok := result.(error); ok {
		return err
	}
	return nil
	{{- else if .HasSingleReturn}}
	if typed, ok := result.({{.SingleReturnType}}); ok {
		return typed
	}
	panic("aop: unexpected result type for {{.Name}}")
	{{- end}}
}
{{- end}}

func init() {
	core.Register[*{{.ProxyName}}]({{.ProxyName}}Container,
		core.WithFactory[*{{.ProxyName}}](func(c ...any) (any, error) {
			{{- if .IsInterface}}
			var target {{.TargetName}}
			if t, err := core.GetByName[{{.TargetName}}]({{$.ProxyName}}Container, ""); err == nil {
				target = t
			}
			{{- else}}
			target := &{{.TargetName}}{}
			{{- end}}
			return New{{.ProxyName}}(target), nil
		}),
	)
}
`

// adviceAdapterTemplate 通知适配器模板
const adviceAdapterTemplate = `// Code generated by goaop. DO NOT EDIT.
//go:build goaop
// +build goaop

package {{.Package}}

import (
	"github.com/xudefa/enhance/aop"
)

{{- range .Adapters}}
func {{.FuncName}}(jp aop.JoinPoint{{if .IsAround}}, proceed aop.ProceedFunc{{end}}) {{if .HasReturn}}any{{end}} {
	aspect := &{{.AspectType}}{}
	{{- if .IsAround}}
	return aspect.{{.MethodName}}(jp, proceed)
	{{- else}}
	aspect.{{.MethodName}}(jp)
	{{- end}}
}
{{- end}}
`

// unused import guard
var _ = strings.TrimSpace
